import { ArrowLeftIcon } from '@heroicons/react/outline';
import { doc, onSnapshot } from 'firebase/firestore';
import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { CommentModal } from '../../components/CommentModal';
import { PostComponent, PostProps } from '../../components/Post';
import { SidebarComponent } from '../../components/Sidebar';
import { WidgetsCompont } from '../../components/Widgets';
import { db } from '../../firebase';

export interface ArticleProp {
  title: string;
  urlToImage: string;
  source: {
    id: string | null;
    name: string;
  };
  author: string;
  description: string;
  url: string;
  publishedAt: string;
  content: string;
}

export interface UserProps {
  name: {
    first: string;
    last: string;
    title: string;
  };
  login: {
    username: string;
  };
  picture: {
    large: string;
    medium: string;
    thumbnail: string;
  };
  email: string;
}

interface Props {
  newsResults: {
    status: string;
    totalResults: number;
    articles: ArticleProp[];
  };
  usersResults: {
    results: UserProps[];
    info: any;
  };
}

const PostPage: NextPage<Props> = ({ newsResults, usersResults }) => {
  const router = useRouter();
  const id = router.query.id as string;
  const [post, setPost] = useState<PostProps | null>(null);

  useEffect(() => {
    onSnapshot(doc(db, 'posts', id), (snapshot: any) => {
      setPost(snapshot);
    });
  }, [db, id]);

  return (
    <div>
      <Head>
        <title>Post Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
        <SidebarComponent />

        {/* Post part */}
        <div className="xl:ml-[370px] border-l border-r xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl border-gray-200">
          {/* Feed Head */}
          <div className="flex items-center px-3 py-2 sticky top-0 z-50 bg-white border-b border-gray-300">
            <div className="hover-effects" onClick={() => router.push('/')}>
              <ArrowLeftIcon className="h-5" />
            </div>
            <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
              Post
            </h2>
          </div>
          <PostComponent id={id} post={post} />
        </div>

        {/* Widgets */}
        <WidgetsCompont
          newsResults={newsResults.articles}
          usersResults={usersResults.results}
        />

        {/* CommentModal */}
        <CommentModal />
      </main>
    </div>
  );
};

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
// show some random news
export const getServerSideProps: GetServerSideProps = async () => {
  const newsResults = await fetch(
    `https://saurav.tech/NewsAPI/top-headlines/category/business/us.json`
  ).then((res) => {
    // console.log(res.json());
    return res.json();
  });

  // https://randomuser.me/api/?results=50&inc=name,login,picture,email
  // who to follow section
  const randomUsersResults = await fetch(
    `https://randomuser.me/api/?results=50&inc=name,login,picture,email`
  ).then((res) => {
    return res.json();
  });

  return {
    props: {
      newsResults: newsResults,
      usersResults: randomUsersResults,
    },
  };
};

export default PostPage;
