import type { NextPage } from 'next';
import Head from 'next/head';
import { FeedComponent } from '../components/Feed';
import { SidebarComponent } from '../components/Sidebar';
import { WidgetsCompont } from '../components/Widgets';

export interface ArticleProp {
  source: {
    id: string | null;
    name: string;
  };
  author: string;
  title: string;
  description: string;
  url: string;
  urlToImage: string;
  publishedAt: string;
  content: string;
}
interface Props {
  newsResults: {
    status: string;
    totalResults: number;
    articles: ArticleProp;
  };
}
const Home: NextPage<Props> = ({ newsResults }) => {
  return (
    <div>
      <Head>
        <title>Home Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
        <SidebarComponent />

        {/* Feed */}
        <FeedComponent />

        {/* Widgets */}
        <WidgetsCompont newsResults={newsResults.articles} />
      </main>
    </div>
  );
};

export default Home;

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
  const newsResults = await fetch(
    `https://saurav.tech/NewsAPI/top-headlines/category/business/us.json`
  ).then((res) => {
    // console.log(res.json());
    return res.json();
  });

  return {
    props: {
      newsResults: newsResults,
    },
  };
}
