import type { NextPage } from 'next';
import Head from 'next/head';
import { FeedComponent } from '../components/Feed';
import { SidebarComponent } from '../components/Sidebar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen max-w-7xl mx-auto">
        {/* Sidebar */}
        <SidebarComponent />

        {/* Feed */}
        <FeedComponent />

        {/* Widgets */}
      </main>
    </div>
  );
};

export default Home;
