import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { FeedComponent } from '../components/Feed';
import { SidebarComponent } from '../components/Sidebar';
import { WidgetsCompont } from '../components/Widgets';

export interface ArticleProp {
  title: string;
  urlToImage: string;
  source: {
    id: string | null;
    name: string;
  };
  author: string;
  description: string;
  url: string;
  publishedAt: string;
  content: string;
}

export interface UserProps {
  name: {
    first: string;
    last: string;
    title: string;
  };
  login: {
    username: string;
  };
  picture: {
    large: string;
    medium: string;
    thumbnail: string;
  };
  email: string;
}

interface Props {
  newsResults: {
    status: string;
    totalResults: number;
    articles: ArticleProp[];
  };
  usersResults: {
    results: UserProps[];
    info: any;
  };
}
const Home: NextPage<Props> = ({ newsResults, usersResults }) => {
  return (
    <div>
      <Head>
        <title>Home Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
        <SidebarComponent />

        {/* Feed */}
        <FeedComponent />

        {/* Widgets */}
        <WidgetsCompont
          newsResults={newsResults.articles}
          usersResults={usersResults.results}
        />
      </main>
    </div>
  );
};

export default Home;

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
// show some random news
export const getServerSideProps: GetServerSideProps = async () => {
  const newsResults = await fetch(
    `https://saurav.tech/NewsAPI/top-headlines/category/business/us.json`
  ).then((res) => {
    // console.log(res.json());
    return res.json();
  });

  // https://randomuser.me/api/?results=50&inc=name,login,picture,email
  // who to follow section
  const randomUsersResults = await fetch(
    `https://randomuser.me/api/?results=50&inc=name,login,picture,email`
  ).then((res) => {
    return res.json();
  });

  return {
    props: {
      newsResults: newsResults,
      usersResults: randomUsersResults,
    },
  };
};
